// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as GiphsListContainer$ReactTemplate from "./GiphsListContainer.bs.js";

function initialState() {
  return /* record */[/* currentText */""];
}

function onInputChange(e, param) {
  var target = e.target;
  return Curry._1(param[/* send */3], /* SearchTextChange */[target.value]);
}

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* currentText */action[0]]]);
}

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, React.createElement("input", {
                              autoFocus: true,
                              placeholder: "Search gifs…",
                              value: self[/* state */1][/* currentText */0],
                              onChange: Curry._1(self[/* handle */0], onInputChange)
                            }), ReasonReact.element(/* None */0, /* None */0, GiphsListContainer$ReactTemplate.make(self[/* state */1][/* currentText */0], /* array */[])));
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  initialState ,
  onInputChange ,
  reducer ,
  component ,
  make ,
  
}
/* component Not a pure module */
